# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "guanr98"
repo_name: "tellm-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    'agent':
        filters: ['LLM based agents', 'Large Language Model based agents', 'LLM agent']
    'llm':
        filters: ['Large Language Model, llm']
    'moe':
        filters: ['Mixture of experts, MoE']
    'SSMs':
        filters: ['State Space Models, SSMs']
    'Communication Intelligence':
        filters: ['5G, LLM', '6G, LLM']
    'RAG':
        filters: ['RAG', 'Retriever Augment Generation', 'RAG, LLM']
    'text2sql':
        filters: ['text2sql', 'nl2sql']
    'AIOps':
        filters: ['AIOps, llm']
    'PPC':
        filters: ['Privacy-Preserving', 'Federated Learning']    
