# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "guanr98"
repo_name: "tellm-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: './docs/agent-arxiv-daily.json'

md_readme_path: 'README.md'


keywords:
    "agent":
        filters: ["LLM based agents", "Large Language Model based agents,LLM agent"]
    "llm":
        filters: ["Large Language Model"]
    "Wireless Network":
        filters: ["Large Language Model", "Wireless Network"]
    "Wireless Communications":
        filters: ["Large Language Model", "Wireless Communications"]
    "Wireless Intelligence":
        filters: ["Large Language Model", "Wireless Intelligence"] 
    "RAG":
        filters: ["Large Language Model", "RAG", "Retriever Augment Generation"]
    "text2sql":
        filters: ["Large Language Model", "text2sql", "nl2sql"]
